### PR TITLE
bump up docutils in docs builds

### PR DESCRIPTION
**Pull request by IAlibay**
Investigate #16 a bit more

### CODE REVIEW

**Comment by lilyminium** [comment]
Unfortunately we're stuck with lower docutils until sphinx-rtd-theme updates: https://github.com/readthedocs/sphinx_rtd_theme/issues/1516

**Comment by orbeckst** [comment]
Is this issue still blocked/current?

**Comment by orbeckst** [comment]
(Possibly not because I removed docutils version info with my merge...)

**Comment by orbeckst** [comment]
Sorry, I probably misunderstood this PR's purpose. I am adding docutils back in...

**Pull request closed without merging**
