### PR TITLE
Fixed testing dependencies in deploy.yaml

### PR DESCRIPTION
**Pull request by ianmkenney**
Changes made in this Pull Request:

 - "pyest" changed to "pytest"
 - Added MDAnalysisTests

PR Checklist
------------
 - [ ] Tests?
 - [ ] Docs?
 - [ ] CHANGELOG updated?
 - [ ] Issue raised/referenced?

### CODE REVIEW

**Review by IAlibay — CHANGES_REQUESTED** [review]
Can you change "shell" on line 18 to just be "bash" please?

**Review by IAlibay — APPROVED** [review]
cheers!

**Comment by ianmkenney** [comment]
Do we want to install sklearn for testing as well?

**Comment by IAlibay** [comment]
> Do we want to install sklearn for testing as well?

sure!

**Review by IAlibay — APPROVED** [review]

**Pull request merged**
